// This file is @generated by build.rs
// DO NOT EDIT MANUALLY

use std::collections::HashMap;
use std::path::PathBuf;

pub fn get_std_sources() -> HashMap<PathBuf, &'static str> {
    let mut map = HashMap::new();
    map.insert(PathBuf::from("yaml.si"), include_str!("../../std/yaml.si"));
    map.insert(PathBuf::from("print.si"), include_str!("../../std/print.si"));
    map.insert(PathBuf::from("json.si"), include_str!("../../std/json.si"));
    map.insert(PathBuf::from("toml.si"), include_str!("../../std/toml.si"));
    map.insert(PathBuf::from("env.si"), include_str!("../../std/env.si"));
    map.insert(PathBuf::from("println.si"), include_str!("../../std/println.si"));
    map.insert(PathBuf::from("io.si"), include_str!("../../std/io.si"));
    map.insert(PathBuf::from("random.si"), include_str!("../../std/random.si"));
    map
}
